services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: npm run build:dev
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./tailwind.config.js:/app/tailwind.config.js
    ports:
      - "3000:3000" # Porta para o Live Server (opcional)