# Conteúdo CORRIGIDO para: docker-compose.yml

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules