# Conteúdo CORRIGIDO para: docker-compose.yml

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      # CORREÇÃO: Mapeia a porta 5173 do seu computador
      # para a porta 8080 DENTRO do container, onde o Vite está rodando.
      - "5173:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules