"""Add sectors table and link to squads

Revision ID: 2f0fcacffe31
Revises: fa6a31bcb885
Create Date: 2025-09-25 17:48:05.299114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0fcacffe31'
down_revision: Union[str, Sequence[str], None] = 'fa6a31bcb885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sectors_id'), ['id'], unique=False)

    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_squads_sector_id', 'sectors', ['sector_id'], ['id'])
        batch_op.drop_index('ix_squads_sector')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_squads_sector_id', type_='foreignkey')
        batch_op.create_index('ix_squads_sector', ['sector'], unique=False)
        batch_op.drop_column('sector_id')

    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sectors_id'))

    op.drop_table('sectors')
    # ### end Alembic commands ###
