"""Add squad_task_type_association table

Revision ID: 319315b44427
Revises: 2f0fcacffe31
Create Date: 2025-09-25 20:41:02.332901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319315b44427'
down_revision: Union[str, Sequence[str], None] = '2f0fcacffe31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squad_task_type_association',
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('task_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.ForeignKeyConstraint(['task_type_id'], ['legal_one_task_types.id'], ),
    sa.PrimaryKeyConstraint('squad_id', 'task_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squad_task_type_association')
    # ### end Alembic commands ###
