"""Remove unique constraint from squad sector

Revision ID: 33d6168709d5
Revises: a4e1b2c3d0f4
Create Date: 2025-09-25 14:40:26.484736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d6168709d5'
down_revision: Union[str, Sequence[str], None] = 'a4e1b2c3d0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.alter_column('external_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_squad_members_legal_one_user_id'))

    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.alter_column('external_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('sector',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_squads_sector'))
        batch_op.create_index(batch_op.f('ix_squads_sector'), ['sector'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_squads_last_assigned_member_id_squad_members'), type_='foreignkey')
        batch_op.drop_column('last_assigned_member_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_assigned_member_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_squads_last_assigned_member_id_squad_members'), 'squad_members', ['last_assigned_member_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_squads_sector'))
        batch_op.create_index(batch_op.f('ix_squads_sector'), ['sector'], unique=1)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('sector',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('external_id',
               existing_type=sa.String(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_squad_members_legal_one_user_id'), ['legal_one_user_id'], unique=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('external_id',
               existing_type=sa.String(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
