"""create task_parent_groups table

Revision ID: 36d039859189
Revises: 319315b44427
Create Date: 2025-09-26 12:10:29.084649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d039859189'
down_revision: Union[str, Sequence[str], None] = '319315b44427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_parent_groups_table = op.create_table('task_parent_groups',
        sa.Column('id', sa.Integer(), nullable=False, comment='Corresponde ao parent_id de legal_one_task_types'),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        # O UniqueConstraint foi removido para permitir nomes duplicados como "Prazo".
    )
    with op.batch_alter_table('task_parent_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_parent_groups_id'), ['id'], unique=False)

    # ### Seeding the initial data provided by the user ###
    op.bulk_insert(task_parent_groups_table,
        [
            {'id': 1, 'name': 'Audiência'},
            {'id': 2, 'name': 'Prazo'},
            {'id': 3, 'name': 'Diversos'},
            {'id': 4, 'name': 'Publicação'},
            {'id': 5, 'name': 'Serviço'},
            {'id': 6, 'name': 'Reunião'},
            {'id': 7, 'name': 'Pesquisa/Estudos'},
            {'id': 8, 'name': 'Prazo'},
            {'id': 9, 'name': 'Intimação Eletrônica'},
            {'id': 10, 'name': 'Workflow'},
            {'id': 11, 'name': 'Acompanhamento Processual'},
            {'id': 12, 'name': 'BB Réu'},
            {'id': 13, 'name': 'Ativos Réu'},
            {'id': 14, 'name': 'Ativos Autor'},
            {'id': 15, 'name': 'BB Autor'},
            {'id': 16, 'name': 'BB Recurso'},
            {'id': 17, 'name': 'BB Encerramento'},
            {'id': 18, 'name': 'BB Acordos'},
            # ID 19 está vazio na lista do usuário, então será pulado.
            {'id': 20, 'name': 'Bradesco'},
            {'id': 21, 'name': 'Banese'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_parent_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_parent_groups_id'))

    op.drop_table('task_parent_groups')
    # ### end Alembic commands ###
