"""add input_data to batch_items

Revision ID: 7822842bb65b
Revises: b29f9b5c9e87
Create Date: 2026-02-09 11:03:45.411100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7822842bb65b'
down_revision: Union[str, Sequence[str], None] = 'b29f9b5c9e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_corequisite_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_corequisite_rules_id'))

    op.drop_table('task_corequisite_rules')
    with op.batch_alter_table('lotes_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes_itens', schema=None) as batch_op:
        batch_op.drop_column('input_data')

    op.create_table('task_corequisite_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('primary_subtype_id', sa.INTEGER(), nullable=False),
    sa.Column('secondary_subtype_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['primary_subtype_id'], ['legal_one_task_subtypes.id'], ),
    sa.ForeignKeyConstraint(['secondary_subtype_id'], ['legal_one_task_subtypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_corequisite_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_corequisite_rules_id'), ['id'], unique=False)

    # ### end Alembic commands ###
