"""Criação da estrutura inicial do banco de dados

Revision ID: a00000000000
Revises:
Create Date: 2025-09-26 12:09:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00000000000'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_one_offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False, comment="ID original da entidade no Legal One"),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True, comment="Caminho completo, ex: 'Jurídico / Filial SP / Contencioso'"),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_one_offices_external_id'), 'legal_one_offices', ['external_id'], unique=True)
    op.create_index(op.f('ix_legal_one_offices_id'), 'legal_one_offices', ['id'], unique=False)

    op.create_table('legal_one_task_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False, comment="ID original da entidade no Legal One"),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_one_task_types_external_id'), 'legal_one_task_types', ['external_id'], unique=True)
    op.create_index(op.f('ix_legal_one_task_types_id'), 'legal_one_task_types', ['id'], unique=False)
    op.create_index(op.f('ix_legal_one_task_types_parent_id'), 'legal_one_task_types', ['parent_id'], unique=False)

    op.create_table('legal_one_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False, comment="ID original do usuário no Legal One"),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_one_users_email'), 'legal_one_users', ['email'], unique=True)
    op.create_index(op.f('ix_legal_one_users_external_id'), 'legal_one_users', ['external_id'], unique=True)
    op.create_index(op.f('ix_legal_one_users_id'), 'legal_one_users', ['id'], unique=False)
    op.create_index(op.f('ix_legal_one_users_name'), 'legal_one_users', ['name'], unique=False)

    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sectors_id'), 'sectors', ['id'], unique=False)

    op.create_table('task_parent_groups',
    sa.Column('id', sa.Integer(), nullable=False, comment="Corresponde ao 'parent_id' usado nos tipos de tarefa do Legal One"),
    sa.Column('name', sa.String(), nullable=False, comment="O nome do grupo de tarefas, ex: 'Audiência', 'Prazo'"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_parent_groups_id'), 'task_parent_groups', ['id'], unique=False)

    op.create_table('squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_squads_id'), 'squads', ['id'], unique=False)

    op.create_table('squad_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('legal_one_user_id', sa.Integer(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['legal_one_user_id'], ['legal_one_users.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squad_members_id'), 'squad_members', ['id'], unique=False)

    op.create_table('squad_task_type_association',
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('task_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.ForeignKeyConstraint(['task_type_id'], ['legal_one_task_types.id'], ),
    sa.PrimaryKeyConstraint('squad_id', 'task_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squad_task_type_association')
    op.drop_index(op.f('ix_squad_members_id'), table_name='squad_members')
    op.drop_table('squad_members')
    op.drop_index(op.f('ix_squads_id'), table_name='squads')
    op.drop_table('squads')
    op.drop_index(op.f('ix_task_parent_groups_id'), table_name='task_parent_groups')
    op.drop_table('task_parent_groups')
    op.drop_index(op.f('ix_sectors_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_legal_one_users_name'), table_name='legal_one_users')
    op.drop_index(op.f('ix_legal_one_users_id'), table_name='legal_one_users')
    op.drop_index(op.f('ix_legal_one_users_external_id'), table_name='legal_one_users')
    op.drop_index(op.f('ix_legal_one_users_email'), table_name='legal_one_users')
    op.drop_table('legal_one_users')
    op.drop_index(op.f('ix_legal_one_task_types_parent_id'), table_name='legal_one_task_types')
    op.drop_index(op.f('ix_legal_one_task_types_id'), table_name='legal_one_task_types')
    op.drop_index(op.f('ix_legal_one_task_types_external_id'), table_name='legal_one_task_types')
    op.drop_table('legal_one_task_types')
    op.drop_index(op.f('ix_legal_one_offices_id'), table_name='legal_one_offices')
    op.drop_index(op.f('ix_legal_one_offices_external_id'), table_name='legal_one_offices')
    op.drop_table('legal_one_offices')
    # ### end Alembic commands ###