"""feat: Adiciona tabelas para log de execucoes em lote

Revision ID: a52b0ededde9
Revises: eb2500839a91
Create Date: 2025-10-08 12:21:17.579206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52b0ededde9'
down_revision: Union[str, Sequence[str], None] = 'eb2500839a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes_execucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotes_execucao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotes_execucao_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lotes_execucao_source'), ['source'], unique=False)

    op.create_table('lotes_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('process_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_task_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['lotes_execucao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotes_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotes_itens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lotes_itens_process_number'), ['process_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotes_itens_process_number'))
        batch_op.drop_index(batch_op.f('ix_lotes_itens_id'))

    op.drop_table('lotes_itens')
    with op.batch_alter_table('lotes_execucao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotes_execucao_source'))
        batch_op.drop_index(batch_op.f('ix_lotes_execucao_id'))

    op.drop_table('lotes_execucao')
    # ### end Alembic commands ###
