"""add legal_one_users_table

Revision ID: c5a3a4b1e0d2
Revises: b3fa8d0a28ee
Create Date: 2025-09-23 14:30:00.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a3a4b1e0d2'
down_revision: Union[str, None] = 'b3fa8d0a28ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_one_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False, comment='ID original do usuário no Legal One'),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_one_users_email'), 'legal_one_users', ['email'], unique=True)
    op.create_index(op.f('ix_legal_one_users_external_id'), 'legal_one_users', ['external_id'], unique=True)
    op.create_index(op.f('ix_legal_one_users_id'), 'legal_one_users', ['id'], unique=False)
    op.create_index(op.f('ix_legal_one_users_name'), 'legal_one_users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_one_users_name'), table_name='legal_one_users')
    op.drop_index(op.f('ix_legal_one_users_id'), table_name='legal_one_users')
    op.drop_index(op.f('ix_legal_one_users_external_id'), table_name='legal_one_users')
    op.drop_index(op.f('ix_legal_one_users_email'), table_name='legal_one_users')
    op.drop_table('legal_one_users')
    # ### end Alembic commands ###