"""Simplify squad models for internal management

Revision ID: fa6a31bcb885
Revises: 33d6168709d5
Create Date: 2025-09-25 13:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fa6a31bcb885'
down_revision: Union[str, None] = '33d6168709d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.alter_column('legal_one_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_squad_members_external_id')
        batch_op.drop_column('role')
        batch_op.drop_column('name')
        batch_op.drop_column('is_active')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('squads', schema=None) as batch_op:
        # --- CORREÇÃO AQUI ---
        # Damos um nome explícito para a restrição de unicidade.
        batch_op.create_unique_constraint('uq_squads_name', ['name'])
        batch_op.drop_index('ix_squads_external_id')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(length=36), nullable=False))
        # --- CORREÇÃO AQUI ---
        # Usamos o mesmo nome para remover a restrição.
        batch_op.drop_constraint('uq_squads_name', type_='unique')
        batch_op.create_index('ix_squads_external_id', ['external_id'], unique=1)

    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_squad_members_external_id', ['external_id'], unique=1)
        batch_op.alter_column('legal_one_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###