"""Seed da tabela de custas recursais 2026 (27 TJs)

Revision ID: rcr002_seed_custas
Revises: rcr001_analise_recursal
Create Date: 2026-07-01

Carga inicial das custas de preparo (Apelação/Agravo) por UF, a partir do
levantamento do operador (planilha 2026). Valores em R$; percentual sobre o
valor da causa quando aplicável; faixas aproximadas por ajuste linear.
Idempotente: só semeia se a tabela estiver vazia. Edições futuras via API
(POST /recursal/custas). PORTE assumido 0 (processo eletrônico).
"""

from alembic import op
import sqlalchemy as sa


revision = "rcr002_seed_custas"
down_revision = "rcr001_analise_recursal"
branch_labels = None
depends_on = None

SEED = [   {   'uf': 'AC',
        'tribunal': 'TJAC',
        'tipo_recurso': 'APELACAO',
        'percentual': 2,
        'valor_fixo': 0,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Taxa 2% do valor (Prov. 15/2026)',
        'ativo': True},
    {   'uf': 'AC',
        'tribunal': 'TJAC',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 420,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Taxa 2% do valor (Prov. 15/2026)',
        'ativo': True},
    {   'uf': 'AL',
        'tribunal': 'TJAL',
        'tipo_recurso': 'APELACAO',
        'percentual': 2,
        'valor_fixo': 0,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Baixa — Taxa 2% (CCP Web); valor exato só no sistema',
        'ativo': True},
    {   'uf': 'AL',
        'tribunal': 'TJAL',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 16.59,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Baixa — Taxa 2% (CCP Web); valor exato só no sistema',
        'ativo': True},
    {   'uf': 'AM',
        'tribunal': 'TJAM',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 999.68,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$999,68 (Lei 7.492/2025)',
        'ativo': True},
    {   'uf': 'AM',
        'tribunal': 'TJAM',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 999.68,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$999,68 (Lei 7.492/2025)',
        'ativo': True},
    {   'uf': 'AP',
        'tribunal': 'TJAP',
        'tipo_recurso': 'APELACAO',
        'percentual': 4.375,
        'valor_fixo': 312.5,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Tab. III por faixa (750@10k / 2.500@50k) — ajuste linear',
        'ativo': True},
    {   'uf': 'BA',
        'tribunal': 'TJBA',
        'tipo_recurso': 'APELACAO',
        'percentual': 3.09425,
        'valor_fixo': 345.575,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Tabela por faixa (655@10k / 1.892,70@50k) — ajuste linear',
        'ativo': True},
    {   'uf': 'BA',
        'tribunal': 'TJBA',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 421.22,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Tabela por faixa (655@10k / 1.892,70@50k) — ajuste linear',
        'ativo': True},
    {   'uf': 'CE',
        'tribunal': 'TJCE',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 314.94,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$314,94 (base UFIRCE)',
        'ativo': True},
    {   'uf': 'CE',
        'tribunal': 'TJCE',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 314.94,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$314,94 (base UFIRCE)',
        'ativo': True},
    {   'uf': 'DF',
        'tribunal': 'TJDF',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 24.3,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Ato de recurso R$24,30 (Regimento; PagCustas)',
        'ativo': True},
    {   'uf': 'DF',
        'tribunal': 'TJDF',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 48.34,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Ato de recurso R$24,30 (Regimento; PagCustas)',
        'ativo': True},
    {   'uf': 'ES',
        'tribunal': 'TJES',
        'tipo_recurso': 'APELACAO',
        'percentual': 1,
        'valor_fixo': 0,
        'valor_minimo': 666.67,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 1% do valor, mín. 135 VRTE (R$666,67)',
        'ativo': True},
    {   'uf': 'ES',
        'tribunal': 'TJES',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 666.67,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 1% do valor, mín. 135 VRTE (R$666,67)',
        'ativo': True},
    {   'uf': 'GO',
        'tribunal': 'TJGO',
        'tipo_recurso': 'APELACAO',
        'percentual': 0.5,
        'valor_fixo': 649.5,
        'valor_minimo': 750.37,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Custa R$649,50 + taxa 0,5% (piso total R$750,37)',
        'ativo': True},
    {   'uf': 'GO',
        'tribunal': 'TJGO',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0.5,
        'valor_fixo': 649.5,
        'valor_minimo': 750.37,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Custa R$649,50 + taxa 0,5% (piso total R$750,37)',
        'ativo': True},
    {   'uf': 'MA',
        'tribunal': 'TJMA',
        'tipo_recurso': 'APELACAO',
        'percentual': 4,
        'valor_fixo': 0,
        'valor_minimo': None,
        'valor_maximo': 1069.37,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 4% do valor, teto R$1.069,37',
        'ativo': True},
    {   'uf': 'MA',
        'tribunal': 'TJMA',
        'tipo_recurso': 'AGRAVO',
        'percentual': 4,
        'valor_fixo': 0,
        'valor_minimo': None,
        'valor_maximo': 1069.37,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 4% do valor, teto R$1.069,37',
        'ativo': True},
    {   'uf': 'MG',
        'tribunal': 'TJMG',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 486.35,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$486,35 (apelação)',
        'ativo': True},
    {   'uf': 'MG',
        'tribunal': 'TJMG',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 347.39,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$486,35 (apelação)',
        'ativo': True},
    {   'uf': 'MS',
        'tribunal': 'TJMS',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 1649.7,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 30 UFERMS (R$1.649,70) — base UFERMS',
        'ativo': True},
    {   'uf': 'MS',
        'tribunal': 'TJMS',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 824.85,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 30 UFERMS (R$1.649,70) — base UFERMS',
        'ativo': True},
    {   'uf': 'MT',
        'tribunal': 'TJMT',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 515.61,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Fixo R$515,61 (inclui porte)',
        'ativo': True},
    {   'uf': 'MT',
        'tribunal': 'TJMT',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 412.49,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Fixo R$515,61 (inclui porte)',
        'ativo': True},
    {   'uf': 'PA',
        'tribunal': 'TJPA',
        'tipo_recurso': 'APELACAO',
        'percentual': 1,
        'valor_fixo': 404,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Taxa 1% + atos (base 2025 — aplicar reajuste)',
        'ativo': True},
    {   'uf': 'PA',
        'tribunal': 'TJPA',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 449.72,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Taxa 1% + atos (base 2025 — aplicar reajuste)',
        'ativo': True},
    {   'uf': 'PB',
        'tribunal': 'TJPB',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 147.08,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 2 UFR-PB (R$147,08)',
        'ativo': True},
    {   'uf': 'PB',
        'tribunal': 'TJPB',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 73.54,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 2 UFR-PB (R$147,08)',
        'ativo': True},
    {   'uf': 'PE',
        'tribunal': 'TJPE',
        'tipo_recurso': 'APELACAO',
        'percentual': 3,
        'valor_fixo': 0,
        'valor_minimo': 314.06,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Custas 2% + taxa 1% (piso R$314,06)',
        'ativo': True},
    {   'uf': 'PE',
        'tribunal': 'TJPE',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 374.31,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Custas 2% + taxa 1% (piso R$314,06)',
        'ativo': True},
    {   'uf': 'PI',
        'tribunal': 'TJPI',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 0,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Baixa — Valor só no sistema COBJUD; agravo isento de taxa',
        'ativo': True},
    {   'uf': 'PR',
        'tribunal': 'TJPR',
        'tipo_recurso': 'APELACAO',
        'percentual': 1,
        'valor_fixo': 0,
        'valor_minimo': 512,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 1% do valor, mín. R$512 (apelação)',
        'ativo': True},
    {   'uf': 'PR',
        'tribunal': 'TJPR',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 387,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 1% do valor, mín. R$512 (apelação)',
        'ativo': True},
    {   'uf': 'RJ',
        'tribunal': 'TJRJ',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 992.38,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$992,38 (Tabela por faixa)',
        'ativo': True},
    {   'uf': 'RJ',
        'tribunal': 'TJRJ',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 1090.54,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$992,38 (Tabela por faixa)',
        'ativo': True},
    {   'uf': 'RN',
        'tribunal': 'TJRN',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 28.94,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — R$28,94 até R$50k (acima: R$57,89 — faixa)',
        'ativo': True},
    {   'uf': 'RN',
        'tribunal': 'TJRN',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 28.94,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — R$28,94 até R$50k (acima: R$57,89 — faixa)',
        'ativo': True},
    {   'uf': 'RO',
        'tribunal': 'TJRO',
        'tipo_recurso': 'APELACAO',
        'percentual': 3,
        'valor_fixo': 0,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 3% do valor (recurso)',
        'ativo': True},
    {   'uf': 'RO',
        'tribunal': 'TJRO',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 459.33,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 3% do valor (recurso)',
        'ativo': True},
    {   'uf': 'RR',
        'tribunal': 'TJRR',
        'tipo_recurso': 'APELACAO',
        'percentual': 2,
        'valor_fixo': 0,
        'valor_minimo': 257.65,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — 2% do valor, piso 5 URP (R$257,65)',
        'ativo': True},
    {   'uf': 'RR',
        'tribunal': 'TJRR',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 515.3,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — 2% do valor, piso 5 URP (R$257,65)',
        'ativo': True},
    {   'uf': 'RS',
        'tribunal': 'TJRS',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 400,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — 8 URC (~R$400) apelação; 4 URC agravo',
        'ativo': True},
    {   'uf': 'RS',
        'tribunal': 'TJRS',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 200,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — 8 URC (~R$400) apelação; 4 URC agravo',
        'ativo': True},
    {   'uf': 'SC',
        'tribunal': 'TJSC',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 720,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$720,00 (recurso cível)',
        'ativo': True},
    {   'uf': 'SC',
        'tribunal': 'TJSC',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 720,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — Preparo fixo R$720,00 (recurso cível)',
        'ativo': True},
    {   'uf': 'SE',
        'tribunal': 'TJSE',
        'tipo_recurso': 'APELACAO',
        'percentual': 0.1522,
        'valor_fixo': 197.81,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Faixa (213,03@10k / 273,91@50k) — ajuste linear',
        'ativo': True},
    {   'uf': 'SE',
        'tribunal': 'TJSE',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0.1522,
        'valor_fixo': 197.81,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Faixa (213,03@10k / 273,91@50k) — ajuste linear',
        'ativo': True},
    {   'uf': 'SP',
        'tribunal': 'TJSP',
        'tipo_recurso': 'APELACAO',
        'percentual': 4,
        'valor_fixo': 0,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 4% do valor (preparo)',
        'ativo': True},
    {   'uf': 'SP',
        'tribunal': 'TJSP',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 576.3,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Alta — 4% do valor (preparo)',
        'ativo': True},
    {   'uf': 'TO',
        'tribunal': 'TJTO',
        'tipo_recurso': 'APELACAO',
        'percentual': 0,
        'valor_fixo': 96,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Faixa baixa R$6–96 (usado teto R$96); calculadora oficial',
        'ativo': True},
    {   'uf': 'TO',
        'tribunal': 'TJTO',
        'tipo_recurso': 'AGRAVO',
        'percentual': 0,
        'valor_fixo': 48,
        'valor_minimo': None,
        'valor_maximo': None,
        'porte_remessa_retorno': 0,
        'vigencia': '2026',
        'fundamentacao': 'Média — Faixa baixa R$6–96 (usado teto R$96); calculadora oficial',
        'ativo': True}]


def upgrade() -> None:
    bind = op.get_bind()
    if not sa.inspect(bind).has_table("recursal_custas"):
        return
    total = bind.execute(sa.text("SELECT COUNT(*) FROM recursal_custas")).scalar()
    if total and total > 0:
        return  # já populado — não sobrescreve
    t = sa.table(
        "recursal_custas",
        sa.column("uf", sa.String), sa.column("tribunal", sa.String),
        sa.column("tipo_recurso", sa.String), sa.column("percentual", sa.Numeric),
        sa.column("valor_fixo", sa.Numeric), sa.column("valor_minimo", sa.Numeric),
        sa.column("valor_maximo", sa.Numeric), sa.column("porte_remessa_retorno", sa.Numeric),
        sa.column("vigencia", sa.String), sa.column("fundamentacao", sa.Text),
        sa.column("ativo", sa.Boolean),
    )
    op.bulk_insert(t, SEED)


def downgrade() -> None:
    op.execute("DELETE FROM recursal_custas WHERE vigencia = '2026'")
