from enum import Enum


class EvidenceSource(str, Enum):
    DATAJUD = "DATAJUD"
    DJEN = "DJEN"
    COMUNICA = "COMUNICA"
    INTERNAL = "INTERNAL"


class ProcessAnalyticalStatus(str, Enum):
    MONITORED = "MONITORED"
    DECISION_EVENT = "DECISION_EVENT"
    RECURSAL_ATTENTION = "RECURSAL_ATTENTION"
    NEAR_TRANSIT = "NEAR_TRANSIT"
    STRONG_TRANSIT_INDICATIVE = "STRONG_TRANSIT_INDICATIVE"
    ELIGIBLE_FOR_OPERATIONAL_CLOSURE = "ELIGIBLE_FOR_OPERATIONAL_CLOSURE"
    CLOSURE_CONFIRMED = "CLOSURE_CONFIRMED"


class QueuePriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class QueueStatus(str, Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    VALIDATED = "VALIDATED"
    DISMISSED = "DISMISSED"
    CONFIRMED = "CONFIRMED"
